# 4.1 NumPy ndarray: 다차원 배열 객체

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[ 1.03878223, -0.23976484,  0.79668475],
       [-1.40896451, -1.40884339,  0.94344067]])

In [4]:
data * 10

array([[ 10.3878223 ,  -2.39764842,   7.96684747],
       [-14.08964511, -14.08843392,   9.43440669]])

In [5]:
data + data

array([[ 2.07756446, -0.47952968,  1.59336949],
       [-2.81792902, -2.81768678,  1.88688134]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

## 4.1.1 ndarray 생성

In [9]:
data1 = [6, 7.5, 8, 0, 1]

In [11]:
arr1 = np.array(data1)

In [12]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [13]:
data1.shape

AttributeError: 'list' object has no attribute 'shape'

In [14]:
arr1.shape

(5,)

In [15]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [23]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [24]:
np.empty((2,3,2))

array([[[  1.50706481e-312,   0.00000000e+000],
        [  8.76794447e+252,   2.15895723e+227],
        [  6.48224638e+170,   3.67145870e+228]],

       [[  8.98703936e-096,   9.03292329e+271],
        [  9.08366793e+223,   1.41075687e+232],
        [  1.16070543e-028,   2.59818961e-306]]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 4.1.2 ndarray의 자료형

In [35]:
arr1 = np.array([1,2,3], dtype = np.float64)

In [36]:
arr1

array([ 1.,  2.,  3.])

In [37]:
arr1.dtype

dtype('float64')

In [38]:
arr2 = np.array([1,2,3], dtype = np.int32)

In [39]:
arr2.dtype

dtype('int32')

In [40]:
arr = np.array([1,2,3,4,5])

In [41]:
arr.dtype

dtype('int32')

In [42]:
float_arr = arr.astype(np.float64)

In [43]:
float_arr.dtype

dtype('float64')

## 4.1.3 배열과 스칼라 간의 연산

In [46]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [47]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [48]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [49]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [50]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [51]:
arr ** 5

array([[  1.00000000e+00,   3.20000000e+01,   2.43000000e+02],
       [  1.02400000e+03,   3.12500000e+03,   7.77600000e+03]])

## 4.1.4 색인과 슬라이싱 기초

In [53]:
arr = np.arange(10)

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[5]

5

In [56]:
arr[5:8]

array([5, 6, 7])

In [57]:
arr[5:8] = 12

In [58]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [59]:
arr_slice = arr[5:8]

In [60]:
arr_slice[1]

12

In [61]:
arr_slice[1] = 12345

In [62]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [63]:
arr_slice[:] = 64

In [64]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [65]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [66]:
arr2d[2]

array([7, 8, 9])

In [67]:
arr2d[0][2]

3

In [69]:
arr2d[0,2]

3

In [70]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [71]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
old_alues = arr3d[0].copy()

In [75]:
arr3d[0]=42

In [76]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[0] = old_alues

In [79]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [83]:
arr2d[1, :2]

array([4, 5])

In [84]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

## 4.1.5 불리언 색인

In [85]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [86]:
data = np.random.randn(7,4)

In [87]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [88]:
data

array([[ 1.74667471,  0.36476131,  0.03035838,  0.45513754],
       [-0.22854593, -0.35220217,  0.91316844, -1.8260143 ],
       [-0.29959168,  1.3947727 , -0.52402744, -0.86571726],
       [ 0.50480973, -1.20637623, -0.28458966,  2.23354649],
       [ 2.46500386,  0.55783413, -0.50519375,  0.97764668],
       [-0.50750779,  0.10660311, -0.95100283, -0.12107727],
       [ 0.14229542, -0.10883483, -0.62942482,  1.2570082 ]])

In [89]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [91]:
data[names == 'Bob']

array([[ 1.74667471,  0.36476131,  0.03035838,  0.45513754],
       [ 0.50480973, -1.20637623, -0.28458966,  2.23354649]])

In [92]:
data[names == 'Bob', 2:]

array([[ 0.03035838,  0.45513754],
       [-0.28458966,  2.23354649]])

In [93]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [95]:
data[~(names == 'Bob')]

array([[-0.22854593, -0.35220217,  0.91316844, -1.8260143 ],
       [-0.29959168,  1.3947727 , -0.52402744, -0.86571726],
       [ 2.46500386,  0.55783413, -0.50519375,  0.97764668],
       [-0.50750779,  0.10660311, -0.95100283, -0.12107727],
       [ 0.14229542, -0.10883483, -0.62942482,  1.2570082 ]])

In [96]:
mask = (names == 'Bob') | (names == 'Will')

In [97]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [98]:
data[mask]

array([[ 1.74667471,  0.36476131,  0.03035838,  0.45513754],
       [-0.29959168,  1.3947727 , -0.52402744, -0.86571726],
       [ 0.50480973, -1.20637623, -0.28458966,  2.23354649],
       [ 2.46500386,  0.55783413, -0.50519375,  0.97764668]])

In [99]:
data[names != 'Joe'] = 7

In [100]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.22854593, -0.35220217,  0.91316844, -1.8260143 ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.50750779,  0.10660311, -0.95100283, -0.12107727],
       [ 0.14229542, -0.10883483, -0.62942482,  1.2570082 ]])

## 4.1.6 팬시 색인

In [101]:
arr = np.empty((8,4))

In [102]:
for i in range(8):
    arr[i] = i

In [103]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [105]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [107]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [108]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [109]:
arr = np.arange(32).reshape((8,4))

In [110]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [112]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [122]:
arr[1]

array([4, 5, 6, 7])

In [127]:
arr[[1,5,7,2]][:,[0,3,1,3]]

array([[ 4,  7,  5,  7],
       [20, 23, 21, 23],
       [28, 31, 29, 31],
       [ 8, 11,  9, 11]])

In [126]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

## 4.1.7 배열 전치와 축 바꾸기

In [128]:
arr = np.arange(15).reshape(3,5)

In [129]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [130]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [131]:
arr = np.random.randn(6,3)

In [132]:
np.dot(arr.T, arr)

array([[  6.19453057,  -3.32572152,   2.0962363 ],
       [ -3.32572152,   4.27248131,  -5.25479138],
       [  2.0962363 ,  -5.25479138,  14.98362656]])

In [133]:
arr = np.arange(16).reshape(2,2,4)

In [134]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [135]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [136]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [137]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])